server:
  port: 8001
  servlet:
    context-path: /demo
    session:
      timeout: 300     # session最大超时时间(分钟)，默认为30
  tomcat:
    uri-encoding: UTF-8
    max-threads:  1000  # tomcat最大线程数，默认为200

# Spring
spring:
  application:
    name: demo
  transaction:
    rollback-on-commit-failure: true
  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java #重启目录

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource   #这里是配置druid连接池，以下都是druid的配置信息
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: abcd@1234
    filters: stat
    initialSize: 100
    maxActive: 1000
    maxOpenPreparedStatements: 20
    maxWait: 60000
    minEvictableIdleTimeMillis: 300000
    minIdle: 500
    poolPreparedStatements: true
    testOnBorrow: false
    testOnReturn: false
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000
    validationQuery: SELECT 1 FROM DUAL

  #设置静态资源路径，多个以逗号分隔
  resources:
    static-locations: classpath:static/,file:static/

  #ThymeLeaf配置
  thymeleaf:
    #模板的模式，支持 HTML, XML TEXT JAVASCRIPT
    mode: HTML5
    #编码 可不用配置
    encoding: UTF-8
    #内容类别,可不用配置
    content-type: text/html
    #开发配置为false,避免修改模板还要重启服务器
    cache: false
    #配置模板路径，默认是templates，可以不用配置
    #    prefix: classpath:/templates
    prefix: classpath:/static/pages/
    suffix: .html
    check-template-location: true


# mybatis-plus
mybatis-plus:
  # 指定全局配置文件位置
  config-location: classpath:/mybatis-config.xml
  # 指定sql映射文件位置
  #  mapper-locations: classpath:/mapper/*.xml
  mapper-locations: classpath*:/com/imooc/demo/mapper/xml/*.xml


#自己定义的配置
test:
  name: zhangsan
  password: 123456

#第三方CAS配置信息，用于获取CAS内部子系统的数据而不被拦截
otherCas:
  username: xnhdfx
  password: 2e9b1b1428a9a249d8f1c50c213cbbf5
  #  casServerPath: http://192.168.0.39:8080/cas
  casServerPath: http://dsjpt.isct.cn:18087/cas
  commonPath: http://dsjpt.isct.cn:18087/common/


