# 默认的profile为dev，其他环境通过指定启动参数使用不同的profile，比如：
#   测试环境：java -jar demo.jar --spring.profiles.active=test
#   生产环境：java -jar demo.jar --spring.profiles.active=prod

server:
  port: 8001 #指定启动端口号
  servlet:
    context-path: /demo

spring:
  application:
    name: demo
  profiles:
    active: dev #默认环境(开发环境)

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource   #这里是配置druid连接池，以下都是druid的配置信息
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: abcd@1234

mybatis:
  mapper-locations: classpath*:/mapper/*    #把xml文件放在com.XX.mapper.*中可能会出现找不到的问题，这里把他放在resource下的mapper中
  typeAliasesPackage: com.imooc.demo.domain        #这里是实体类的位置，#实体扫描，多个package用逗号或者分号分隔
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
logging:
  file: test-service.log
  level:
    com.test: debug
#自己定义的配置
test:
  name:
  password:
  testmodel:
    id: 1
    host-port: 127.0.0.1:8080

--- #注意前面有短横线

#测试环境###########################################################################################################################################
spring:
  application:
    name: demo
  profiles: test #测试环境

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource   #这里是配置druid连接池，以下都是druid的配置信息
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: abcd@1234

mybatis:
  mapper-locations: classpath*:/mapper/*    #把xml文件放在com.XX.mapper.*中可能会出现找到的问题，这里把他放在resource下的mapper中
  typeAliasesPackage: com.imooc.demo.domain         #这里是实体类的位置，#实体扫描，多个package用逗号或者分号分隔
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
logging:
  file: test-service.log
  level:
    com.test: debug

--- #注意前面的短横线

#正式环境###########################################################################################################################################
spring:
  application:
    name: demo
  profiles: prod

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    username: test
    password: abcd@1234

mybatis:
  mapper-locations: classpath*:/mapper/*
  typeAliasesPackage: com.imooc.demo.domain
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

logging:
  file: test-service.log
  level:
    com.test: debug