server:
  port: 8081
  #  项目访问前缀
  servlet:
    context-path: /demo
    session:
      timeout: 300     # session最大超时时间(分钟)，默认为30
  tomcat:
    uri-encoding: UTF-8
    max-threads:  1000  # tomcat最大线程数，默认为200

# Spring
spring:
  application:
    name: demo
  transaction:
    rollback-on-commit-failure: true
  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java #重启目录
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource   #这里是配置druid连接池，以下都是druid的配置信息
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    filters: stat
    initialSize: 100
    maxActive: 1000
    maxOpenPreparedStatements: 20
    maxWait: 60000
    minEvictableIdleTimeMillis: 300000
    minIdle: 500
    poolPreparedStatements: true
    testOnBorrow: false
    testOnReturn: false
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000
    validationQuery: SELECT 1 FROM DUAL

  #设置静态资源路径，多个以逗号分隔
  resources:
    static-locations: classpath:static/,file:static/

  #ThymeLeaf配置
  thymeleaf:
    #模板的模式，支持 HTML, XML TEXT JAVASCRIPT
    mode: HTML5
    #编码 可不用配置
    encoding: UTF-8
    #内容类别,可不用配置
    content-type: text/html
    #开发配置为false,避免修改模板还要重启服务器
    cache: false
    #配置模板路径，默认是templates，可以不用配置
    #    prefix: classpath:/templates
    prefix: classpath:/static/pages/
    suffix: .html
    check-template-location: true

# 单独集成cas 实现单点登录
#cas:
#  server-url-prefix: http://192.168.0.249:18080/cas
#  server-login-url: http://192.168.0.249:18080/cas/login
#  client-host-url: http://192.168.0.39:18080
#  use-session: true
#  validation-type: CAS
#ignore-host-url: (/register.jsp)|(/user/*)|(/imUser/*)|(/toolKit/*)|(/download/*)|(/js/*)|(/images/*)|(/view/*)|(/css/*)|(/easyui/*)
#casClientLogoutUrl: http://192.168.0.249:8080/cas/logout?service=http://192.168.0.39:18080/common


# shiro-cas 配置   cas做单点登录认证  shiro做授权
shiro:
  # 在访问cas服务器登录之后，会返回一个ticket。由该地址接收
  casFilterUrlPattern: /shiro-cas
  # cas服务前缀
  casServerUrlPrefix: http://192.168.0.249:18080/cas
  # shiro服务前缀
  shiroServerUrlPrefix: http://192.168.0.39:8081/demo
  # 登录地址
  loginUrl: ${shiro.casServerUrlPrefix}/login?service=${shiro.shiroServerUrlPrefix}${shiro.casFilterUrlPattern}
  # 登出地址
  logoutUrl: ${shiro.casServerUrlPrefix}/logout?service=${shiro.shiroServerUrlPrefix}${shiro.casFilterUrlPattern}

# shiro放行白名单
shiro-ignorl-url:
  urls:
  - /css/**
  - /js/**
  - /images/**
  - /fonts/**
  - /layui/**
  - /user/**
  - /menu.json

#各子系统地址
systemUrl:
  casUrl: http://192.168.0.249:18080/cas
  demoUrl: http://192.168.0.39:8081/demo

# mybatis-plus
mybatis-plus:
  # 指定全局配置文件位置
  config-location: classpath:/mybatis-config.xml
  # 指定sql映射文件位置
  mapper-locations: classpath:/mapper/*.xml


# 第三方CAS配置信息，用于获取CAS内部子系统的数据而不被拦截
otherCas:
  username: xnhdfx
  password: 2e9b1b1428a9a249d8f1c50c213cbbf5
  casServerPath: http://dsjpt.isct.cn:18087/cas
  commonPath: http://dsjpt.isct.cn:18087/common/

# 统一日志接口
logUrl: http://192.168.0.90:8066/yunjinglog/log/doLog

#自己定义的配置
test:
  name: zhangsan
  password: 123456
