server:
  port: 8001
  servlet:
    context-path: /demo
    session:
      timeout: 300     # session最大超时时间(分钟)，默认为30
  tomcat:
    uri-encoding: UTF-8
    max-threads:  1000  # tomcat最大线程数，默认为200

# Spring
spring:
  transaction:
    rollback-on-commit-failure: true
  application:
    name: demo

  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java #重启目录

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource   #这里是配置druid连接池，以下都是druid的配置信息
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: abcd@1234
    filters: stat
    initialSize: 100
    maxActive: 1000
    maxOpenPreparedStatements: 20
    maxWait: 60000
    minEvictableIdleTimeMillis: 300000
    minIdle: 500
    poolPreparedStatements: true
    testOnBorrow: false
    testOnReturn: false
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000
    validationQuery: SELECT 1 FROM DUAL

  # thymeleaf
  thymeleaf:
    cache: false
    enabled: true
    encoding: UTF-8
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
    servlet:
      content-type: text/html

# Mybatis
mybatis:
  # 指定全局配置文件位置
  config-location: classpath:/mybatis-config.xml
  # 指定sql映射文件位置
  mapper-locations: classpath:/mapper/*.xml


#自己定义的配置
test:
  name: zhangsan
  password: 123456


